# Generated by Django 5.1.4 on 2025-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_prices',
            field=models.JSONField(blank=True, help_text="JSON format: {'295g': 12.99, '300g': 15.99, '350': 18.99}, '500': 28.99}", null=True),
        ),
    ]
