# Generated by Django 5.1.4 on 2025-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_weight_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, help_text="For honey products with weights: e.g., '€14.99 - €29.99'", max_length=50, null=True),
        ),
    ]
